olsws_listen_addr: '*'
olsws_http_port: 80
olsws_https_port: 443

webserver_vhost:
  user: vagrant
  group: vagrant
  domain: example.test
  admin_email: admin@example.com
  lsphp_version: lsphp74
  ssl_enabled: True,
  ssl_certificate: /path/to/ssl/certificate
  ssl_certificate_key: /path/to/ssl/certificate_key
