
- name: Check that the composer command exists
  stat:
    path: /usr/local/bin/composer
  register: composer_stat_result

- name: Download installer
  get_url:
    url: https://getcomposer.org/installer
    sha256sum: 756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3
    dest: ./composer-setup.php
    force: True
  when: not composer_stat_result.stat.exists

- name: Install composer
  shell: |
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/local/bin/composer
  when: not composer_stat_result.stat.exists
