webserver_vhost:
  user: vagrant
  group: vagrant
  domain: wpdev.test
  admin_email: admin@wpdev.test
  lsphp_version: lsphp74
  ssl_enabled: True,
  ssl_certificate: /path/to/ssl/certificate
  ssl_certificate_key: /path/to/ssl/certificate_key

mariadb_default_character_set: utf8mb4
mariadb_client_cnf:
  default-character-set: '{{ mariadb_default_character_set }}'
mariadb_server_cnf:
  character-set-server: '{{ mariadb_default_character_set }}'
  collation-server: '{{ mariadb_default_character_set }}_general_ci'
  slow_query_log: 1
  slow_query_log_file: '/var/log/mysql/mariadb-slow.log'
  long_query_time: 3
  log_error: '/var/log/mysql/error.log'
