webserver_vhost_user: vagrant
webserver_vhost_group: vagrant
webserver_vhost_domain: wpdev.test
webserver_vhost_admin_email: admin@wpdev.test
webserver_vhost_lsphp_version: lsphp74
webserver_vhost_ssl_enabled: true
webserver_vhost_ssl_certificate: /path/to/ssl/certificate
webserver_vhost_ssl_certificate_key: /path/to/ssl/certificate_key

mariadb_default_character_set: utf8mb4
mariadb_client_cnf:
  default-character-set: '{{ mariadb_default_character_set }}'
mariadb_server_cnf:
  character-set-server: '{{ mariadb_default_character_set }}'
  collation-server: '{{ mariadb_default_character_set }}_general_ci'
  slow_query_log: 1
  slow_query_log_file: '/var/log/mysql/mariadb-slow.log'
  long_query_time: 3
  log_error: '/var/log/mysql/error.log'

wordpress_webroot: "/home/{{ webserver_vhost_user }}/web/{{ webserver_vhost_domain }}"
wordpress_front_url: 'http://{{ webserver_vhost_domain }}/'
wordpress_core_url: 'http://{{ webserver_vhost_domain }}/{{ wordpress_dir }}'
wordpress_site_title: 'ローカル開発用ブログ'
wordpress_dbname: 'db1'
wordpress_dbuser: 'db1usr'
wordpress_dbpasswd: '{{ secret.db.passwd }}'
wordpress_dbhost: 'localhost'
