- hosts: remote_machine
  remote_user: "{{ user }}"
  gather_facts: "{{ check_env | default(True) }}"
  become: yes
  become_method: sudo
  vars_files:
    - vars/prod/secret.yml

  roles:
    - openlitespeed
