- name: Update packages
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags: common

- name: Install required packages
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-dev
    - python3-pip
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-pexpect

- name: Use python3 as default version
  shell: |
    update-alternatives --install /usr/bin/python python /usr/bin/python3 1 &&
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 &&
    update-alternatives --set python /usr/bin/python3 &&
    update-alternatives --set pip /usr/bin/pip3

  changed_when: false
